# Generated by Django 4.1.7 on 2024-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='resetToken',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='nombre',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='formacion',
            name='nombre_institucion',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='nivelformacion',
            name='nombre',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='person',
            name='identificacion',
            field=models.CharField(blank=True, max_length=190, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='orcid',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='url_orcid',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='icono',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='resource',
            name='link',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='resource',
            name='method',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='resource',
            name='path',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='rol',
            name='name',
            field=models.CharField(max_length=190, unique=True),
        ),
    ]
