# Generated by Django 4.1.7 on 2024-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenidosolicitud',
            name='palabras_claves',
            field=models.CharField(max_length=251),
        ),
        migrations.AlterField(
            model_name='contenidosolicitud',
            name='resumen',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='revista',
            name='nombre',
            field=models.CharField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='titulo_articulo',
            field=models.CharField(max_length=200),
        ),
    ]
