# Generated by Django 4.2.2 on 2024-07-03 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_alter_contenidosolicitud_palabras_claves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='Keywords',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='agradecimientos',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='introduccion',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='literact_citada',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='materi_metodos',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='palabras_claves',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='result_discu',
        ),
        migrations.RemoveField(
            model_name='contenidosolicitud',
            name='resumen',
        ),
    ]
