# Generated by Django 4.2.2 on 2024-07-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0003_remove_contenidosolicitud_keywords_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenidosolicitud',
            name='declaracion_originalidad',
            field=models.FileField(default=1, upload_to='archivos/archivos_contenido_solicitud/'),
            preserve_default=False,
        ),
    ]
