# Generated by Django 4.1.7 on 2024-05-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexo',
            name='nombre_ane',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='description',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='pqrs',
            name='titulo',
            field=models.CharField(max_length=190),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=190, null=True),
        ),
        migrations.AlterField(
            model_name='tipopqrs',
            name='tipo',
            field=models.CharField(max_length=190),
        ),
    ]
